# -*- coding: utf-8 -*-
"""türkçe_kelime_bulma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14UMD2Kr6hl60FzV-It1Of33B1DhCM0Xs
"""

kelimeler = ['mehmet','emekli','birol','mazı','köy','istanbul','nevşehir','taş','kağıt','makas','duvar','hayalet','sevgi','aşk','ömür','ankara','kapadokya']
alfabe_harfler = 'ABCÇDEFGĞHIİJKLMNOÖPRSTUÜVYZ'

import random
import string

def get_valid_word(kelimeler):
  kelime = random.choice(kelimeler)
  while '-' in kelime or ' ' in kelime:
    kelime = random.choice(kelimeler)
  return kelime

def kelime_bulma():
  kelime = get_valid_word(kelimeler).upper()
  harfler =set(kelime)
  alfabe = set(alfabe_harfler)
  kullanılan_harfler = set()
  çıkma = 0
  while çıkma ==0:
    try:
      lives = int(input('Kaç can olacağını giriniz: '))
      while len(harfler)>0 and lives >0:
        print('Senin kullandığın harfler: ',''.join(kullanılan_harfler))

        kelime_list=[letter if letter in kullanılan_harfler else '-' for letter in kelime]
        print('Aktif kelime:', ' '.join(kelime_list))

        kullanıcı_harf = input('Bir harf tahmini girin:').upper()

        if kullanıcı_harf in alfabe - kullanılan_harfler:
          kullanılan_harfler.add(kullanıcı_harf)
          if kullanıcı_harf in harfler:
              harfler.remove(kullanıcı_harf)
          else:
            lives = lives - 1
            print('Girdiğiniz harf kelime içerisinde bulunmamaktadır.!')
        elif kullanıcı_harf == kullanılan_harfler:
          print('Daha önceden girdiğiniz harfi tekrar girdiniz. Lütfen başka bir harf giriniz.!')
        else:
          print('Lütfen bir harf giriniz!')
      if lives == 0:
        print('Üzgünüm, canınız bitti ve öldünüz.')
        çıkma=1
      else:
        print('Tebrikler, kelimeyi bildiniz',kelime,'!!')
        çıkma=1
    except:
      print('Lütfen bir sayı giriniz!')

kelime_bulma()

